name: Update SwitchyOmega SORL

on:
  schedule:
    # 每 12 小时的第 7 分钟运行一次 (UTC 时间)
    - cron: '7 */12 * * *'
  workflow_dispatch: # 允许手动触发执行

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # 赋予推送权限

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run conversion script
        run: python convert.py

      - name: Commit and Push
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add proxy_list.sorl
          if git diff --cached --quiet; then
            echo "没有内容更新"
          else
            git commit -m "Auto-update proxy list $(date +'%Y-%m-%d %H:%M')"
            git push
          fi
