# .github/workflows/cleanup-workflow-runs.yml

name: 'Cleanup Old Workflow Runs'

# 控制此工作流何时运行
on:
  # 允许你手动从 Actions 标签页运行此工作流
  workflow_dispatch:
  # 使用 cron 语法定时触发，这里设置为每小时的第30分钟执行一次
  # 这能确保清理任务被频繁执行，以满足 "48小时" 的精确要求
  schedule:
    - cron: '30 * * * *'

jobs:
  cleanup:
    runs-on: ubuntu-latest
    # 授予删除 workflow runs 的权限
    permissions:
      actions: write

    steps:
      - name: 'Delete old workflow runs'
        uses: nerd-company/delete-workflow-runs@v3
        with:
          # 【重要】GITHUB_TOKEN 是必须的，用于 API 认证
          token: ${{ secrets.GITHUB_TOKEN }}
          
          # 要操作的仓库，默认为当前仓库，所以通常不用写
          # repository: ${{ github.repository }}

          # 【核心配置】保留的小时数。这里设置为48，精确满足你的需求
          retain_hours: 48
          
          # 你还可以添加其他过滤条件，例如：
          # 只清理已完成(completed)且失败(failure)的运行记录
          # keep_minimum_runs: 0 # 覆盖其他保留规则，至少保留0个
          # delete_workflow_pattern: 'Your-Workflow-Name' # 只清理特定名称的工作流
          # delete_run_by_conclusion_pattern: 'failure,cancelled,skipped' # 只清理失败、取消或跳过的
