name: Update Ad-Blocking Rules

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Checkout repository
        uses: actions/checkout@v4

      - name: 2. Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 3. [DEBUG] List files to check requirements.txt existence
        run: ls -la

      - name: 4. [DEBUG] Display content of requirements.txt
        run: cat requirements.txt

      - name: 5. Install dependencies using a clean, single-line command
        run: python -m pip install -r requirements.txt

      - name: 6. Run merge script
        run: python merge_rules.py

      - name: 7. Commit and push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: Auto-update merged ad-blocking rules"
          file_pattern: merged_rules.txt
          commit_user_name: GitHub Actions Bot
          commit_user_email: actions@github.com
          commit_author: GitHub Actions Bot <actions@github.com>
