# 工作流名称
name: Update Ad-Blocking Rules

# 工作流触发条件
on:
  # 允许手动从 Actions 页面触发
  workflow_dispatch:
  # 定时任务：每天 UTC 时间 00:00 运行一次 (北京时间早上8点)
  schedule:
    - cron: '0 0 * * *'

# 定义工作任务
jobs:
  build-and-commit:
    # 运行环境
    runs-on: ubuntu-latest

    # 任务步骤
    steps:
      # 第一步：检出你的仓库代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 第二步：设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # 你可以选择合适的 Python 版本

      # 第三步：安装脚本依赖 (从 requirements.txt 文件)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 第四步：运行你的 Python 脚本来生成合并后的规则文件
      - name: Run merge script
        run: python merge_rules.py

      # 第五步：自动提交变更
      - name: Commit and push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          # 提交信息
          commit_message: "chore: Auto-update merged ad-blocking rules"
          # 要添加的文件，这里是脚本生成的那个文件
          file_pattern: merged_rules.txt
          # 提交作者信息
          commit_user_name: GitHub Actions Bot
          commit_user_email: actions@github.com
          commit_author: GitHub Actions Bot <actions@github.com>
